package com.digitalcrafts.syntel.controller;

import com.digitalcrafts.syntel.model.Product;
import com.digitalcrafts.syntel.services.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;


@RestController
public class ProductController {

    @Autowired
    ProductService productService;

    @RequestMapping("/product")
    public Optional<Product> productLookup(@RequestParam(value = "id", required = true) long queryID) {
        return productService.getProduct(queryID);
    }

    @RequestMapping("/products")
    public Iterable<Product> productListLookup() {
        return productService.getAllProducts();
    }

    @RequestMapping(value = "/product", method = RequestMethod.POST)
    public String addProduct(@RequestBody Product product) {
        return productService.addNewProduct(product);
    }


//    @Autowired // This means to get the bean called userRepository
//    // Which is auto-generated by Spring, we will use it to handle the data
//    private ProductRepository productRepository;
//
//    @GetMapping(path="/product") // Map ONLY GET Requests
//    @ResponseBody
//    public Optional<Product> getProduct (@RequestParam(value = "id", required = true) long queryID){
//        return productRepository.findById(queryID);
//    }
//
//    @GetMapping(path="/products")
//    public @ResponseBody Iterable<Product> getAllProducts() {
//        // This returns a JSON or XML with the users
//        return productRepository.findAll();
//    }
//
//    @PostMapping(path="/product")
//    @ResponseBody
//    public String addNewProduct (@RequestBody Product product){
//        productRepository.save(product);
//        return "Saved";
//    }
}