package com.digitalcrafts.syntel.controller;

import com.digitalcrafts.syntel.model.Product;
import com.digitalcrafts.syntel.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;


@RestController
public class ProductLookupController {

//    @Autowired
//    ProductLookupService productLookupService;
//
//    @RequestMapping("/product")
//    public Product productLookup(@RequestParam(value = "id", required = true) long queryID) {
//        return productLookupService.productLookupServiceById(queryID);
//    }
//
//    @RequestMapping("/products")
//    public List<Product> productListLookup() {
//        return productLookupService.productLookupListAll();
//    }
//
//    @RequestMapping(value = "/addproduct", method = RequestMethod.POST)
//    public void addProduct(@RequestBody Product product) {
//        productLookupService.addProduct(product);
//    }


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;

    @GetMapping(path="/product") // Map ONLY GET Requests
    @ResponseBody
    public Optional<Product> getProduct (@RequestParam(value = "id", required = true) long queryID){
        return productRepository.findById(queryID);
    }

    @GetMapping(path="/products")
    public @ResponseBody Iterable<Product> getAllProducts() {
        // This returns a JSON or XML with the users
        return productRepository.findAll();
    }

    @PostMapping(path="/product")
    @ResponseBody
    public String addNewProduct (@RequestBody Product product){
        productRepository.save(product);
        return "Saved";
    }
}